# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class F1Dump < Formula
  desc "UDP Data Dumper for Formula 1 game"
  homepage "https://github.com/racing-telemetry"
  version "0.0.1-rc.0"
  license "Apache"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/racing-telemetry/f1-cli/releases/download/v0.0.1-rc.0/f1-dump_Darwin_x86_64.tar.gz"
      sha256 "dd1b20046a7643f43bad3fcfb896d9444565131ba00305e316084ab5b1409e87"

      def install
        bin.install "f1dump"
        bash_completion.install "completions/f1dump.bash" => "f1dump"
        zsh_completion.install "completions/f1dump.zsh" => "_f1dump"
        fish_completion.install "completions/f1dump.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/racing-telemetry/f1-cli/releases/download/v0.0.1-rc.0/f1-dump_Darwin_arm64.tar.gz"
      sha256 "26568b01acf683b4a409510ac2b813070354ae4045a3358df68611c2be34c707"

      def install
        bin.install "f1dump"
        bash_completion.install "completions/f1dump.bash" => "f1dump"
        zsh_completion.install "completions/f1dump.zsh" => "_f1dump"
        fish_completion.install "completions/f1dump.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/racing-telemetry/f1-cli/releases/download/v0.0.1-rc.0/f1-dump_Linux_armv7.tar.gz"
      sha256 "d75da98a70faeed90984082c9beff1e39029108b4ef1a9315afc07cca8fa9b97"

      def install
        bin.install "f1dump"
        bash_completion.install "completions/f1dump.bash" => "f1dump"
        zsh_completion.install "completions/f1dump.zsh" => "_f1dump"
        fish_completion.install "completions/f1dump.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/racing-telemetry/f1-cli/releases/download/v0.0.1-rc.0/f1-dump_Linux_x86_64.tar.gz"
      sha256 "b52cd0cf837187bed2fdcee888864155f41c116ce0cf2859fa171ace96cabf8e"

      def install
        bin.install "f1dump"
        bash_completion.install "completions/f1dump.bash" => "f1dump"
        zsh_completion.install "completions/f1dump.zsh" => "_f1dump"
        fish_completion.install "completions/f1dump.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/racing-telemetry/f1-cli/releases/download/v0.0.1-rc.0/f1-dump_Linux_arm64.tar.gz"
      sha256 "42c950eb8fc1e660b9977ec30ee03bbf609b87a33725fd065944ed7bedc65d4b"

      def install
        bin.install "f1dump"
        bash_completion.install "completions/f1dump.bash" => "f1dump"
        zsh_completion.install "completions/f1dump.zsh" => "_f1dump"
        fish_completion.install "completions/f1dump.fish"
      end
    end
  end

  depends_on "go" => :optional

  test do
    system "#{bin}/f1dump version"
  end
end
